### ISSUE TITLE
Camel 4.9 - Add support for code completion for global data formats

### ISSUE THREAD

**Issue by davsclaus** [camel-tooling/camel-idea-plugin#1071]
You can configure <dataFormats> in XML DSL and in YAML DSL now that are outside the routes. This makes it possible to configure them once globally, and then reuse in the routes.

```
<camel>

    <dataFormats>
        <base64 id="myBase2" lineLength="60" urlSafe="true"/>
    </dataFormats>

    <route>
        <from uri="direct:start"/>
        <marshal><custom ref="myBase2"/></marshal>
        <to uri="mock:result"/>
    </route>

</camel>
```

Inside `<dataFormats>` you want code completion for the 50+ data formats that are in Camel and how to configure them.

The same for YAML DSL:

```
- dataFormats:
  - base64:
      id: df1
      lineLength: 88
  - csv:
      id: df2
      headerDisabled: true
      ignoreEmptyLines: true

```
